# Generated by Django 6.0.6 on 2026-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addSupplier',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=50)),
                ('contactperson', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gstno', models.CharField(blank=True, max_length=15, null=True)),
                ('druglicence', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cusignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('profession', models.CharField(choices=[('Customer', 'Customer'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist'), ('Nurse', 'Nurse'), ('Hospital Staff', 'Hospital Staff'), ('Clinic Staff', 'Clinic Staff'), ('Medical Representative', 'Medical Representative'), ('Other', 'Other')], default='profession', max_length=50)),
                ('organization', models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Pharmacy', 'Pharmacy'), ('Medical Store', 'Medical Store'), ('Nursing Home', 'Nursing Home'), ('Diagnostic Laboratory', 'Diagnostic Laboratory'), ('Medical College', 'Medical College'), ('Healthcare Company', 'Healthcare Company'), ('Pharmaceutical Company', 'Pharmaceutical Company'), ('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler'), ('NGO / Health Organization', 'NGO / Health Organization'), ('Other', 'Other')], default='organization', max_length=50)),
                ('city', models.CharField(default='city', max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'signup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='mddetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, upload_to='medicine_images/')),
                ('mdname', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Suspension', 'Suspension'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Gel', 'Gel'), ('Lotion', 'Lotion'), ('Drops', 'Drops'), ('Spray', 'Spray'), ('Inhaler', 'Inhaler'), ('Powder', 'Powder'), ('Sachet', 'Sachet'), ('Granules', 'Granules'), ('Mouthwash', 'Mouthwash'), ('Gargle', 'Gargle'), ('Solution', 'Solution'), ('Emulsion', 'Emulsion'), ('Infusion', 'Infusion'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Shampoo', 'Shampoo'), ('Soap', 'Soap'), ('Other', 'Other')], max_length=50)),
                ('packingsize', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=50)),
                ('description', models.TextField()),
                ('used', models.TextField()),
                ('sideeffect', models.TextField()),
                ('prescription', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('expirydate', models.DateField()),
            ],
        ),
    ]
