# Generated by Django 6.0.6 on 2026-07-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='signup',
        ),
    ]
