# Generated by Django 6.0.6 on 2026-07-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='signup',
        ),
    ]
