# Generated by Django 6.0.6 on 2026-07-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='mddetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='medicine_images/')),
                ('mdname', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'syrup'), ('Tube', 'Tube'), ('Injection', 'Injection')], max_length=50)),
                ('packingsize', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('used', models.CharField(max_length=100)),
                ('sideeffect', models.CharField(max_length=100)),
                ('prescription', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('expirydate', models.DateField()),
            ],
        ),
    ]
