# Generated by Django 6.0.6 on 2026-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mddetail',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mddetail',
            name='sideeffect',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mddetail',
            name='used',
            field=models.TextField(),
        ),
    ]
