# Generated by Django 6.0.6 on 2026-07-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_mddetail_description_alter_mddetail_sideeffect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mddetail',
            name='image',
            field=models.ImageField(max_length=500, upload_to='medicine_images/'),
        ),
    ]
