# Generated by Django 6.0.6 on 2026-07-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_mddetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusignup',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='cusignup',
            name='organization',
            field=models.CharField(choices=[('Hospital', 'Hospital'), ('Clinic', 'Clinic'), ('Pharmacy', 'Pharmacy'), ('Medical Store', 'Medical Store'), ('Nursing Home', 'Nursing Home'), ('Diagnostic Laboratory', 'Diagnostic Laboratory'), ('Medical College', 'Medical College'), ('Healthcare Company', 'Healthcare Company'), ('Pharmaceutical Company', 'Pharmaceutical Company'), ('Distributor', 'Distributor'), ('Wholesaler', 'Wholesaler'), ('NGO / Health Organization', 'NGO / Health Organization'), ('Other', 'Other')], default='organization', max_length=50),
        ),
        migrations.AddField(
            model_name='cusignup',
            name='profession',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist'), ('Nurse', 'Nurse'), ('Hospital Staff', 'Hospital Staff'), ('Clinic Staff', 'Clinic Staff'), ('Medical Representative', 'Medical Representative'), ('Other', 'Other')], default='profession', max_length=50),
        ),
    ]
