# Generated by Django 6.0.6 on 2026-07-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_cusignup_city_cusignup_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mddetail',
            name='form',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Suspension', 'Suspension'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Gel', 'Gel'), ('Lotion', 'Lotion'), ('Drops', 'Drops'), ('Spray', 'Spray'), ('Inhaler', 'Inhaler'), ('Powder', 'Powder'), ('Sachet', 'Sachet'), ('Granules', 'Granules'), ('Mouthwash', 'Mouthwash'), ('Gargle', 'Gargle'), ('Solution', 'Solution'), ('Emulsion', 'Emulsion'), ('Infusion', 'Infusion'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Shampoo', 'Shampoo'), ('Soap', 'Soap'), ('Other', 'Other')], max_length=50),
        ),
    ]
