# Generated by Django 6.0.6 on 2026-07-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_mddetail_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='addSupplier',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=50)),
                ('contactperson', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gstno', models.CharField(blank=True, max_length=15, null=True)),
                ('druglicence', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
    ]
