# Generated by Django 6.0.6 on 2026-07-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineid', models.CharField(max_length=50)),
                ('invoice', models.CharField(max_length=100)),
                ('medicinename', models.CharField(max_length=50)),
                ('batchno', models.CharField(max_length=100)),
                ('currentstock', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Suspension', 'Suspension'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Gel', 'Gel'), ('Lotion', 'Lotion'), ('Drops', 'Drops'), ('Spray', 'Spray'), ('Inhaler', 'Inhaler'), ('Powder', 'Powder'), ('Sachet', 'Sachet'), ('Granules', 'Granules'), ('Mouthwash', 'Mouthwash'), ('Gargle', 'Gargle'), ('Solution', 'Solution'), ('Emulsion', 'Emulsion'), ('Infusion', 'Infusion'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Shampoo', 'Shampoo'), ('Soap', 'Soap'), ('Other', 'Other')], max_length=100)),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('newstock', models.CharField(max_length=100)),
                ('purchasedate', models.DateField()),
                ('supplier', models.CharField(max_length=50)),
                ('expiredate', models.DateField()),
                ('status', models.CharField(choices=[('In stock', 'In stock'), ('Out of stock', 'Out of Stock'), ('Low Stock', 'Los Stock')], max_length=30)),
                ('lastupdate', models.DateField()),
                ('remark', models.TextField(max_length=500)),
            ],
        ),
    ]
