# Generated by Django 6.0.6 on 2026-07-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_stock',
            name='month_year',
            field=models.CharField(default='July,2026', max_length=20),
        ),
    ]
