# Generated by Django 6.0.6 on 2026-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_stock_month_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='out_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineid', models.CharField(max_length=100)),
                ('invoice', models.CharField(max_length=100)),
                ('medicinename', models.CharField(max_length=100)),
                ('batchno', models.CharField(max_length=100)),
                ('currentstock', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('unitprice', models.CharField(max_length=100)),
                ('outstock', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('customername', models.CharField(max_length=100)),
                ('expiredate', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('lastdate', models.DateField()),
                ('remark', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='add_stock',
            name='month_year',
        ),
    ]
