# Generated by Django 6.0.6 on 2026-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_out_stock_remove_add_stock_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_stock',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_stock',
            name='currentstock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_stock',
            name='newstock',
            field=models.IntegerField(),
        ),
    ]
