# Generated by Django 6.0.6 on 2026-07-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_stock_totalamount_alter_add_stock_currentstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_stock',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
