# Generated by Django 6.0.6 on 2026-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allopathy_medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Suspension', 'Suspension'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Gel', 'Gel'), ('Lotion', 'Lotion'), ('Drops', 'Drops'), ('Spray', 'Spray'), ('Inhaler', 'Inhaler'), ('Powder', 'Powder'), ('Sachet', 'Sachet'), ('Granules', 'Granules'), ('Mouthwash', 'Mouthwash'), ('Gargle', 'Gargle'), ('Solution', 'Solution'), ('Emulsion', 'Emulsion'), ('Infusion', 'Infusion'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Shampoo', 'Shampoo'), ('Soap', 'Soap'), ('Other', 'Other')], max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('packing_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirydate', models.DateField()),
            ],
            options={
                'db_table': 'allopathy_medicine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ayurvedic_medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('packing_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirydate', models.DateField()),
            ],
            options={
                'db_table': 'ayurvedic_medicine',
                'managed': True,
            },
        ),
    ]
