# Generated by Django 6.0.6 on 2026-07-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allopathy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('packing_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirydate', models.DateField()),
            ],
            options={
                'db_table': 'allopathy_medicine',
            },
        ),
        migrations.CreateModel(
            name='Ayurvedic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('packing_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirydate', models.DateField()),
            ],
            options={
                'db_table': 'Ayurvedic_medicine',
            },
        ),
    ]
