# Generated by Django 6.0.6 on 2026-07-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allopathy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ayurvedic',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='ayurvedic',
            table='ayurvedic_medicine',
        ),
    ]
