# Generated by Django 6.0.6 on 2026-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_allopathy_options_alter_ayurvedic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='allopathy_add',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('packing_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expirydate', models.DateField()),
            ],
            options={
                'db_table': 'allopathy_medicine',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Allopathy',
        ),
    ]
