# Generated by Django 6.0.6 on 2026-07-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_allopathy_delete_allopathy_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='allopathy',
            name='strength',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
