# Generated by Django 6.0.6 on 2026-07-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_allopathy_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allopathy',
            name='strength',
        ),
        migrations.AlterField(
            model_name='allopathy',
            name='packing_size',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
