# Generated by Django 6.0.6 on 2026-07-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_remove_allopathy_strength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allopathy',
            name='packing_size',
            field=models.CharField(default='some_value', max_length=50),
        ),
    ]
