# Generated by Django 6.0.6 on 2026-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_allopathy_medicine_ayurvedic_medicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayurvedic_medicine',
            name='category',
        ),
        migrations.AlterField(
            model_name='allopathy_medicine',
            name='category',
            field=models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Suspension', 'Suspension'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Ointment', 'Ointment'), ('Gel', 'Gel'), ('Lotion', 'Lotion'), ('Drops', 'Drops'), ('Spray', 'Spray'), ('Inhaler', 'Inhaler'), ('Powder', 'Powder'), ('Sachet', 'Sachet'), ('Granules', 'Granules'), ('Mouthwash', 'Mouthwash'), ('Gargle', 'Gargle'), ('Solution', 'Solution'), ('Emulsion', 'Emulsion'), ('Infusion', 'Infusion'), ('Patch', 'Patch'), ('Suppository', 'Suppository'), ('Shampoo', 'Shampoo'), ('Soap', 'Soap'), ('Other', 'Other')], max_length=100),
        ),
    ]
