# Generated by Django 6.0.6 on 2026-07-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0009_remove_ayurvedic_medicine_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayurvedic_medicine',
            name='category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
